### ISSUE TITLE
Attribute "primaryColor" has already been defined error

### ISSUE THREAD

**Issue by alextel69** [neokree/MaterialTabs#29]
Alongside with MaterialTabs I use rengwuxian/MaterialEditText. Both libs use "primaryColor" attribute.
Attribute "primaryColor" has already been defined occurs.

Possible solutions:
1. Replace app:primaryColor with neokree:primaryColor
2. Or pick up primaryColor attr from theme declaration

**Comment by neokree** [comment]
I will use colorPrimary from appcompat version, avariable in the next release

**Comment by alextel69** [comment]
When are you about to roll it out?

2015-01-20 19:52 GMT+02:00 Fabio Biola <notifications@github.com>:

**Comment by rohanraarora** [comment]
I am having exactly same issue.
Any idea when we can expect the update?

**Comment by acostela** [comment]
Hi! I'm having the same issue and I like how it looks your library and I would like to use it. Do you know when are you going to release the new version?

**Comment by alextel69** [comment]
Please reopen this issue. PR proposed solves issue in not the best manner

**Comment by mdzeko** [comment]
The same thing happens with Attribute "color" has already been defined. Probably because of the appcompat-v7 lib. So, yes, consider reopening this issue.
btw this can be a great lib, keep it up

**Comment by Moter8** [comment]
Duplicate of #20, by the way.
